[package]
name = "http-link"
version = "1.0.0"
authors = ["axion014 <axion014@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

percent-encoding = "2.1.0"
take_mut = "0.2.2"
url = "2.1.1"